name: CI

on:
  push:
    branches:
      - "**"
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  elixir-compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project source
        uses: actions/checkout@v4

      - name: Elixir cache
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - run: ls -laht

      - name: Setup elixir
        uses: erlef/setup-beam@v1
        id: setup-elixir
        with:
          otp-version: 25.3
          elixir-version: 1.15.7

      - name: Elixir dependencies
        run: mix deps.get

      - name: Elixir compile
        run: mix compile
